[[agents]]
  id = "test_agent2"
  name = "Agent 2"
  public_address = "HcSCjtqUtBggecrj5iqT9tIRRd4Xtnzjf8oD5Stx6IVshokvdIf79pYjuOxa8mr"
  keystore_file = "./agent2.keystore"

[[dnas]]
  id = "personas_profiles"
  file = "dna/personas-profiles.dna.json"
  hash = "QmPrbyrN6ooU7B9KXygDawWtPGbajVCew8HjiSUcNrE8Vi"

[[dnas]]
  id = "deep_key"
  file = "../DeepKey/dna/deepkey.dna.json"
  hash = "QmPk6gad2h7de2owUimKfQY4ctwtQ73t7ZdaL24f3aAcZB"

[[instances]]
  id = "dpki_happ"
  dna = "deep_key"
  agent = "test_agent2"
[instances.logger]
  type = "simple"
  file = "app_spec.log"
[instances.storage]
  type = "memory"
  path = "tmp-storage"

[[instances]]
  id = "personas-profiles"
  dna = "personas_profiles"
  agent = "test_agent2"
[instances.logger]
  type = "simple"
  file = "app_spec.log"
[instances.storage]
  type = "memory"
  path = "tmp-storage"

[[interfaces]]
  id = "personas_websocket_interface"
[interfaces.driver]
  type = "websocket"
  port = 3402
[[interfaces.instances]]
  id = "personas-profiles"
[[interfaces.instances]]
  id = "dpki_happ"

[dpki]
  instance_id = "dpki_happ"
  init_params = "{\"revocation_key\": \"HcScIXuxtWI6ttc5gngvQTsDnHtynb5dzyDujh37mNo43nf7ZRB5UZKmR9953pa\"}"

# -----------  Networking  -----------
#
# [network]
# type = "n3h"
# n3h_mode = "REAL"
# n3h_persistence_path = "./n3h-agent1"
# n3h_log_level = "i"
# bootstrap_nodes = []
