# -----------  Agents  -----------

[[agents]]
  id = "test_agent2"
  name = "Agent 2"
  public_address = "HcSCIUKodbWktcbmwyAaVrYnsbadi6b9sOV9D4ZoE8i333ZtcGw38Jn3U6u63qi"
  keystore_file = "./agent2.keystore"

# -----------  DNAs  -----------

[[dnas]]
  id = "personas_profiles"
  file = "../identity-manager/dna/personas-profiles.dna.json"
  hash = "QmPrbyrN6ooU7B9KXygDawWtPGbajVCew8HjiSUcNrE8Vi"s

[[dnas]]
  id = "peer_chat_dna"
  file = "./dna/peer-chat.dna.json"
  hash = "QmUyZPprQzthkCKzL8WnT9TxQH5B4WJKejP23TrZcmAbjo"

# -----------  Instances  -----------

[[instances]]
  id = "personas-profiles"
  dna = "personas_profiles"
  agent = "test_agent2"
[instances.storage]
  type = "memory"
[[instances]]
  id = "peer-chat"
  dna = "peer_chat_dna"
  agent = "test_agent2"
[instances.storage]
  type = "memory"

# -----------  Bridges  -----------

[[bridges]]
  caller_id = "peer-chat"
  callee_id = "personas-profiles"
  handle = "p-p-bridge"

# -----------  Interfaces  -----------

[[interfaces]]
  id = "websocket_interface"
[interfaces.driver]
  type = "websocket"
  port = 3404
[[interfaces.instances]]
  id = "peer-chat"
[[interfaces.instances]]
  id = "personas-profiles"

# -----------  Networking  -----------