# -----------  Agents  -----------

[[agents]]
id = "test_agent2"
name = "Agent 2"
public_address = "HcSCIUKodbWktcbmwyAaVrYnsbadi6b9sOV9D4ZoE8i333ZtcGw38Jn3U6u63qi"
keystore_file = "./agent2.keystore"

# -----------  DNAs  -----------
[[dnas]]
  id = "personas_profiles"
  file = "../personas-profiles/dna/personas-profiles-agent2.dna.json"
  hash = "QmYDp1iXZUibuVBKsvooF3Npy3ZnNAKM4SrqM9wTZ7iQ7Z"
[[dnas]]
  id = "deep_key"
  file = "../DeepKey/dna/deepkey.dna.json"
  hash = "QmbdxX9VaX1XYyaDgM36ob3ta96umUifaKJ4ySExxo7ckH"
[[dnas]]
  id = "peer_chat_dna"
  file = "./dna/peer-chat.dna.json"
  hash = "Qmf7mbu7B898UBtLte1y3AB8c6MskpsrV8yWjvyNsXxxSj"

[[instances]]
  id = "dpki_happ"
  dna = "deep_key"
  agent = "test_agent2"
[instances.storage]
  type = "memory"
[[instances]]
  id = "personas-profiles"
  dna = "personas_profiles"
  agent = "test_agent2"
[instances.storage]
  type = "memory"
[[instances]]
  id = "peer-chat"
  dna = "peer_chat_dna"
  agent = "test_agent2"
[instances.storage]
  type = "memory"

[[bridges]]
  caller_id = "peer-chat"
  callee_id = "personas-profiles"
  handle = "p-p-bridge"

[[interfaces]]
  id = "websocket_interface"
[interfaces.driver]
  type = "websocket"
  port = 3402
[[interfaces.instances]]
  id = "dpki_happ"
[[interfaces.instances]]
  id = "peer-chat"
[[interfaces.instances]]
  id = "personas-profiles"

  # -----------  dpki  -----------

[dpki]
  instance_id = "dpki_happ"
  init_params = "{\"revocation_key\": \"HcScIXuxtWI6ttc5gngvQTsDnHtynb5dzyDujh37mNo43nf7ZRB5UZKmR9953pb\"}"

# -----------  Networking  -----------

[network]
  type = "n3h"
  n3h_mode = "REAL"
  n3h_persistence_path = "./n3h-agent2"
  n3h_log_level = "i"
  bootstrap_nodes = []
