# -----------  Agents  -----------

# generate a new keystore using hc keygen or use an existing keystore
# copy the public_address and path to the keystore into the [[agents]] section
# Give yourself an alpha-numeric id with no spaces (_ is ok)
# Enter your name
# [[agents]]
id = "AgentID update the agent property in [[instances]]"
name = "Your agent name here"
public_address = "public addess"
keystore_file = "path/to/keystore"

# -----------  DNA  -----------

[[dnas]]
id = "peer_chat_dna"
file = "./dna/peer-chat.dna.json"
hash = "Qm328wyq38924y"

[[instances]]
id = "peer-chat"
dna = "peer_chat_dna"
agent = "same as id in [[agents]] section above"
[instances.logger]
type = "simple"
file = "app_spec.log"
[instances.storage]
type = "file"
path = "tmp-storage"


[[interfaces]]
id = "websocket_interface"
[interfaces.driver]
type = "websocket"
port = 3400
[[interfaces.instances]]
id = "peer-chat"

# -----------  UI  -----------

[[ui_bundles]]
id = "main"
root_dir = "./ui"
hash = "Qm000"

[[ui_interfaces]]
id = "ui-interface"
bundle = "main"
port = 3000
dna_interface = "websocket_interface"

# -----------  Networking  -----------

[network]
type = "n3h"
n3h_path = ""
n3h_persistence_path = "/tmp"
bootstrap_nodes = []
n3h_log_level = "t"
